export const envConstants = {
  ACCESS_TOKEN_JWT_SECRET: 'ACCESS_TOKEN_JWT_SECRET',
  ACCESS_TOKEN_EXPIRES_IN: 'ACCESS_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_JWT_SECRET: 'REFRESH_TOKEN_JWT_SECRET',
  REFRESH_TOKEN_EXPIRES_IN: 'REFRESH_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_SKIP_INCREMENT_VERSION: 'REFRESH_TOKEN_SKIP_INCREMENT_VERSION',
}
