export const envConstants = {
  // jwt
  ACCESS_TOKEN_JWT_SECRET: 'ACCESS_TOKEN_JWT_SECRET',
  ACCESS_TOKEN_EXPIRES_IN: 'ACCESS_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_JWT_SECRET: 'REFRESH_TOKEN_JWT_SECRET',
  REFRESH_TOKEN_EXPIRES_IN: 'REFRESH_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_SKIP_INCREMENT_VERSION: 'REFRESH_TOKEN_SKIP_INCREMENT_VERSION',
  // ldap
  LDAP_URL: 'LDAP_URL',
  LDAP_BIND_DN: 'LDAP_BIND_DN',
  LDAP_BIND_CREDENTIALS: 'LDAP_BIND_CREDENTIALS',
  LDAP_SEARCH_BASE: 'LDAP_SEARCH_BASE',
  LDAP_SEARCH_FILTER: 'LDAP_SEARCH_FILTER',
  LDAP_SEARCH_ATTRIBUTES: 'LDAP_SEARCH_ATTRIBUTES',
}
