export enum UserRoles {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_USER = 'ROLE_USER',
  // C3_ADMINISTRATOR = 'C3_ADMINISTRATOR',
  // C3_TEACHER = 'C3_TEACHER',
  // C3_PARENT = 'C3_PARENT',
  // C3_STUDENT = 'C3_STUDENT',
};